---
- name: configure virtual server
  a10.acos_axapi.a10_slb_virtual_server:
    ansible_host: "{{ ansible_host }}"
    ansible_port: "{{ ansible_port }}"
    ansible_username: "{{ ansible_username }}"
    ansible_password: "{{ ansible_password }}"
    state: present
    name: VIP-TCP-80
    ip_address: 10.11.0.1
    enable_disable_action: enable
    stats_data_action: stats-data-enable
    port_list:
    - name: ansible_demo
      protocol: tcp
      port_number: 80
      action: enable
      service_group: ansible-servicegroup
